org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

modId=cobblemon_pasturecollector
modCobblemonVersion=1.7.3
modMyVersion=1.4.0-pr1
modName=Cobblemon Pasture Collector
modDescription=Collects items from Pokemon in nearby Pasture Blocks in Cobblemon.
modAuthor=timinc aka Timothy Metcalfe

modIssues=https://github.com/timinc-cobble/cobblemon-pasture-collector/issues
modSource=https://github.com/timinc-cobble/cobblemon-pasture-collector

modDiscord=https://discord.com/invite/WKAR27SdSv

# Mod Properties
mod_version=1.7.3-fabric-1.4.0-pr1
maven_group=us.timinc.mc.cobblemon
archives_base_name=pasturecollector

# Fabric project dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
fabric_kotlin_version=1.13.6+kotlin.2.2.20

#neoforge project dependencies
neoforge_version=21.1.182
kotlin_for_forge_version=5.10.0

# Common dependencies
minecraft_version=1.21.1
cobblemon_version=1.7.3+1.21.1
junit_version=5.1.0
tim_core_fabric_version=1.7.3-fabric-1.32.0
tim_core_neoforge_version=1.7.3-neoforge-1.32.0
droploottables_fabric_version=1.7.3-fabric-1.9.0
droploottables_neoforge_version=1.7.3-neoforge-1.9.0
